include: package:lint/strict.yaml

linter:

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
