targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en-US
          fallback_strategy: base_locale
          input_directory: assets/i18n
          input_file_pattern: .i18n.yaml
          output_directory: lib/i18n
          # output_file_name: translations.g.dart
          # string_interpolation: braces
# 予約語と2faを直す
