name: miria
description: Miria is Misskey Client for Mobile App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.8+30

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_html: 3.0.0-alpha.6
  flutter_riverpod: ^2.3.2
  misskey_dart:
    path: ../misskey_dart
  mfm_renderer:
    path: ../mfm_renderer
  tuple: ^2.0.1
  path_provider: ^2.0.14
  dio: ^5.1.1
  path: ^1.8.2
  auto_route: ^6.0.5
  freezed_annotation: ^2.2.0
  url_launcher: ^6.1.10
  intl: ^0.18.0
  scrollable_positioned_list: ^0.3.6
  kana_kit: ^2.0.0
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.0
  shared_preferences: ^2.1.0
  badges: ^3.1.1
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4
  uuid: ^3.0.7
  file_picker: ^5.3.0
  package_info_plus: ^4.0.0
  reorderables: ^0.6.0
  confetti: ^0.7.0
  flutter_highlighting: ^0.9.0+11.8.0
  highlighting: ^0.9.0+11.8.0
  dotted_border: ^2.0.0+3
  visibility_detector: ^0.4.0+2
  percent_indicator: ^4.2.3
  fl_chart: ^0.62.0
  receive_sharing_intent: ^1.4.5
  share_plus: ^7.0.2
  mfm_parser: ^1.0.3
  flutter_svg: ^2.0.6
  json5: ^0.8.0
  slang: ^3.18.1
  slang_flutter: ^3.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^6.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.2
  slang_build_runner: ^3.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/i18n/
    - assets/i18n/misskey/

fonts:
  - family: KosugiMaru
    fonts:
      - asset: assets/fonts/KosugiMaru-Regular.ttf
        weight: 300
      - asset: assets/fonts/KosugiMaru-Regular.ttf
        weight: 400
      - asset: assets/fonts/KosugiMaru-Regular.ttf
        weight: 500
      - asset: assets/fonts/KosugiMaru-Regular.ttf
        weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
