name: miria
description: Miria is Misskey Client for Mobile App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.13+91

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  colorfilter_generator: ^0.0.8
  confetti: ^0.7.0
  device_info_plus: ^9.0.2
  dio: ^5.1.1
  dotted_border: ^2.0.0+3
  file: ^7.0.0
  file_picker: ^6.0.0
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_colorpicker: ^1.0.3
  flutter_highlighting: ^0.9.0+11.8.0
  flutter_image_compress: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  google_fonts: ^6.1.0
  highlighting: ^0.9.0+11.8.0
  image_editor: ^1.3.0
  image_gallery_saver: ^2.0.3
  intl: ^0.18.0
  json5: ^0.8.0
  json_annotation: ^4.8.0
  kana_kit: ^2.0.0
  media_kit: ^1.1.8+2
  media_kit_libs_video: ^1.0.3
  media_kit_video: ^1.2.1
  mfm: ^1.0.5
  mfm_parser: ^1.0.3
  misskey_dart:
    git: https://github.com/shiosyakeyakini-info/misskey_dart.git
  package_info_plus: ^4.0.0
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^11.0.1
  receive_sharing_intent: ^1.4.5
  reorderables: ^0.6.0
  share_plus: ^7.0.2
  shared_preferences: ^2.1.0
  stack_trace: ^1.11.0
  twemoji_v2: ^0.5.3
  url_launcher: ^6.1.10
  uuid: ^4.1.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.3.0
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.0

dependency_overrides:
  image_editor:
    git:
      url: https://github.com/shiosyakeyakini-info/flutter_image_editor_fix_ios_color_option.git
      path: ./image_editor/
  image_editor_common:
    git:
      url: https://github.com/shiosyakeyakini-info/flutter_image_editor_fix_ios_color_option.git
      path: ./image_editor_common/
  image_editor_platform_interface:
    git:
      url: https://github.com/shiosyakeyakini-info/flutter_image_editor_fix_ios_color_option.git
      path: ./image_editor_platform_interface/


dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.3.3
  cider: ^0.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: ^2.1.2
  mockito: ^5.4.2
  plugin_platform_interface: ^2.1.6
  url_launcher_platform_interface: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon_adaptive.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
