import 'package:flutter/material.dart';

class CheckboxListTileFormField extends FormField<bool> {
  CheckboxListTileFormField({
    super.key,
    super.onSaved,
    super.validator,
    super.initialValue,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    mouseCursor,
    activeColor,
    fillColor,
    checkColor,
    hoverColor,
    overlayColor,
    splashRadius,
    materialTapTargetSize,
    visualDensity,
    focusNode,
    autofocus = false,
    shape,
    side,
    isError = false,
    tileColor,
    title,
    subtitle,
    isThreeLine = false,
    dense,
    secondary,
    selected = false,
    controlAffinity = ListTileControlAffinity.platform,
    contentPadding,
    tristate = false,
    checkboxShape,
    selectedTileColor,
    onFocusChange,
    enableFeedback,
    checkboxSemanticLabel,
  }) : super(
          builder: (state) {
            return CheckboxListTile(
              value: state.value,
              onChanged: state.didChange,
              mouseCursor: mouseCursor,
              activeColor: activeColor,
              fillColor: fillColor,
              checkColor: checkColor,
              hoverColor: hoverColor,
              overlayColor: overlayColor,
              splashRadius: splashRadius,
              materialTapTargetSize: materialTapTargetSize,
              visualDensity: visualDensity,
              focusNode: focusNode,
              autofocus: autofocus,
              shape: shape,
              side: side,
              isError: isError,
              enabled: enabled,
              tileColor: tileColor,
              title: title,
              subtitle: subtitle,
              isThreeLine: isThreeLine,
              dense: dense,
              secondary: secondary,
              selected: selected,
              controlAffinity: controlAffinity,
              contentPadding: contentPadding,
              tristate: tristate,
              checkboxShape: checkboxShape,
              selectedTileColor: selectedTileColor,
              onFocusChange: onFocusChange,
              enableFeedback: enableFeedback,
              checkboxSemanticLabel: checkboxSemanticLabel,
            );
          },
        );
}
