name: デプロイ

on: 
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_for_linux:
    name: Linux用ビルド
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Flutter pub get
        run: flutter pub get

      - name: Get Version
        run: echo "BUMP_VERSION=$(flutter pub run cider version)" >> $GITHUB_ENV

      - name: Setup build env
        run: |
          sudo apt install libsecret-1-dev clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev locate libfuse2
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/
          flutter pub global activate flutter_distributor

      - name: Create AppImage file
        run: |
          flutter_distributor package --platform linux --targets appimage
          mv ./dist/$BUMP_VERSION/miria-$BUMP_VERSION-linux.AppImage ./dist/$BUMP_VERSION/miria-$BUMP_VERSION-amd64.AppImage


      - name: Upload AppImage file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v$BUMP_VERSION ./dist/$BUMP_VERSION/miria-$BUMP_VERSION-amd64.AppImage 