name: デプロイ(snap)
run-name: Building Miria's Snap package
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: ビルド（Snap）
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert Icon image to 256x256
        run:  |
          sudo apt install -y imagemagick
          convert assets/images/icon.png -resize 256x256 snap/gui/miria.png
          rm assets/images/icon_adaptive.png

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build Snap
        id: snapcraft
        uses: diddlesnaps/snapcraft-multiarch-action@v1
        with:
          architecture: ${{ matrix.platform }}

      - name: Get Build Version
        run: |
          echo "VERSION=$(cat pubspec.yaml | grep version | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - name: Upload snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v$VERSION ${{ steps.snapcraft.outputs.snap }}

      # https://github.com/snapcore/action-publish
      # Snap Storeでパッケージ名"miria"を予約後、"SNAPCRAFT_STORE_CREDENTIALS"を登録し、
      # 以下をコメントアウトを解除することでSnap Storeへアップロードすることが可能です。
      # Snap Storeでの公開後は、上記の"Upload snap"をコメントアウトしてください。
      # （通常、SnapファイルをそのままStore外で公開することはありません）
      #
      #- name: Upload snap store
      #  uses: snapcore/action-publish@v1
      #  env:
      #    SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      #  with:
      #    snap: ${{ steps.snapcraft.outputs.snap }}
      #    release: edge
