name: デプロイ(windows zip)

on: 
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_for_windows:
    name: Windows用ビルド
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: |
          git config --system core.longpaths true
          flutter pub get

      - name: Get App Version
        run:  |
          echo "version=$(flutter pub run cider version)" >> $env:GITHUB_ENV
          sed -i "s/VersionNumber/$(flutter pub run cider version)/" windows/innosetup.iss

      - name: Build for Windows
        run: |
          flutter build windows --release

      - name: Copy DLL
        run: |
          cp C:\Windows\System32\msvcp140.dll build\windows\x64\runner\Release\
          cp C:\Windows\System32\vcruntime140.dll build\windows\x64\runner\Release\
          cp C:\Windows\System32\vcruntime140_1.dll build\windows\x64\runner\Release\

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.1.0
        with:
          path: windows/innosetup.iss

      - name: Rename .EXE Installer
        run:  mv miria-installer.exe miria-installer_${env:version}_x64.exe

      - name: Zip files
        run: |
          ren build\windows\x64\runner\Release Miria
          Compress-Archive -Path build\windows\x64\runner\Miria -DestinationPath miria_${env:version}_windows-x64.zip -Force

      - name: Create tag and release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${env:version}  miria_${env:version}_windows-x64.zip miria-installer_${env:version}_x64.exe
